# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import block_pb2 as block__pb2


class NodeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddBlockRequest = channel.unary_unary(
                '/NodeService/AddBlockRequest',
                request_serializer=block__pb2.BlockMessage.SerializeToString,
                response_deserializer=block__pb2.Response.FromString,
                )
        self.AddBlockToChain = channel.unary_unary(
                '/NodeService/AddBlockToChain',
                request_serializer=block__pb2.BlockValidation.SerializeToString,
                response_deserializer=block__pb2.ValidationResponse.FromString,
                )


class NodeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddBlockRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddBlockToChain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddBlockRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBlockRequest,
                    request_deserializer=block__pb2.BlockMessage.FromString,
                    response_serializer=block__pb2.Response.SerializeToString,
            ),
            'AddBlockToChain': grpc.unary_unary_rpc_method_handler(
                    servicer.AddBlockToChain,
                    request_deserializer=block__pb2.BlockValidation.FromString,
                    response_serializer=block__pb2.ValidationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddBlockRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeService/AddBlockRequest',
            block__pb2.BlockMessage.SerializeToString,
            block__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddBlockToChain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NodeService/AddBlockToChain',
            block__pb2.BlockValidation.SerializeToString,
            block__pb2.ValidationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
