# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\"4\n\x0bSmpcMessage\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x16\n\x0e\x64\x61taset_number\x18\x02 \x01(\x05\"\x1f\n\x0cSmpcResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\"\n\x11GobalModelMessage\x12\r\n\x05value\x18\x01 \x01(\x0c\"&\n\x13GlobalModelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32u\n\rClientService\x12\'\n\x08sendSmpc\x12\x0c.SmpcMessage\x1a\r.SmpcResponse\x12;\n\x0fsendGlobalModel\x12\x12.GobalModelMessage\x1a\x14.GlobalModelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SMPCMESSAGE']._serialized_start=16
  _globals['_SMPCMESSAGE']._serialized_end=68
  _globals['_SMPCRESPONSE']._serialized_start=70
  _globals['_SMPCRESPONSE']._serialized_end=101
  _globals['_GOBALMODELMESSAGE']._serialized_start=103
  _globals['_GOBALMODELMESSAGE']._serialized_end=137
  _globals['_GLOBALMODELRESPONSE']._serialized_start=139
  _globals['_GLOBALMODELRESPONSE']._serialized_end=177
  _globals['_CLIENTSERVICE']._serialized_start=179
  _globals['_CLIENTSERVICE']._serialized_end=296
# @@protoc_insertion_point(module_scope)
