# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import client_pb2 as client__pb2


class ClientServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendSmpc = channel.unary_unary(
                '/ClientService/sendSmpc',
                request_serializer=client__pb2.SmpcMessage.SerializeToString,
                response_deserializer=client__pb2.SmpcResponse.FromString,
                )
        self.sendGlobalModel = channel.unary_unary(
                '/ClientService/sendGlobalModel',
                request_serializer=client__pb2.GobalModelMessage.SerializeToString,
                response_deserializer=client__pb2.GlobalModelResponse.FromString,
                )


class ClientServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendSmpc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendGlobalModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClientServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendSmpc': grpc.unary_unary_rpc_method_handler(
                    servicer.sendSmpc,
                    request_deserializer=client__pb2.SmpcMessage.FromString,
                    response_serializer=client__pb2.SmpcResponse.SerializeToString,
            ),
            'sendGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.sendGlobalModel,
                    request_deserializer=client__pb2.GobalModelMessage.FromString,
                    response_serializer=client__pb2.GlobalModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ClientService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClientService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendSmpc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/sendSmpc',
            client__pb2.SmpcMessage.SerializeToString,
            client__pb2.SmpcResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sendGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ClientService/sendGlobalModel',
            client__pb2.GobalModelMessage.SerializeToString,
            client__pb2.GlobalModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
